[modular]
"0" = [
    " _______ ",
    "|  _    |",
    "| | |   |",
    "| | |   |",
    "| |_|   |",
    "|       |",
    "|_______|"
]
"1" = [
    " ____  ",
    "|    | ",
    " |   | ",
    " |   | ",
    " |   | ",
    " |   | ",
    " |___| "
]
"2" = [
    " _______ ",
    "|       |",
    "|____   |",
    " ____|  |",
    "| ______|",
    "| |_____ ",
    "|_______|"
]
"3" = [
    " _______ ",
    "|       |",
    "|___    |",
    " ___|   |",
    "|___    |",
    " ___|   |",
    "|_______|"
]
"4" = [
    " _   ___ ",
    "| | |   |",
    "| |_|   |",
    "|       |",
    "|___    |",
    "    |   |",
    "    |___|"
]
"5" = [
    " _______ ",
    "|       |",
    "|   ____|",
    "|  |____ ",
    "|_____  |",
    " _____| |",
    "|_______|"
]
"6" = [
    " ___     ",
    "|   |    ",
    "|   |___ ",
    "|    _  |",
    "|   | | |",
    "|   |_| |",
    "|_______|"
]
"7" = [
    " _______ ",
    "|       |",
    "|___    |",
    "    |   |",
    "    |   |",
    "    |   |",
    "    |___|"
]
"8" = [
    "  _____  ",
    " |  _  | ",
    " | |_| | ",
    "|   _   |",
    "|  | |  |",
    "|  |_|  |",
    "|_______|"
]
"9" = [
    " _______ ",
    "|  _    |",
    "| | |   |",
    "| |_|   |",
    "|___    |",
    "    |   |",
    "    |___|"
]
":" = [
    " ___  ",
    "|   | ",
    "|___| ",
    " ___  ",
    "|   | ",
    "|___| ",
    "      "
]

[smooth]
"0" = [
    "╭─╮",
    "│││",
    "╰─╯"
]
"1" = [
    "╶╮ ",
    " │ ",
    "╶┴╴"
]
"2" = [
    "╭─╮",
    "╭─╯",
    "╰─╴"
]
"3" = [
    "╭─╮",
    "╶─┤",
    "╰─╯"
]
"4" = [
    "╷ ╷",
    "╰─┤",
    "  ╵"
]
"5" = [
    "╭─╴",
    "╰─╮",
    "╰─╯"
]
"6" = [
    "╭─╮",
    "├─╮",
    "╰─╯"
]
"7" = [
    "╭─╮",
    "  │",
    "  ╵"
]
"8" = [
    "╭─╮",
    "├─┤",
    "╰─╯"
]
"9" = [
    "╭─╮",
    "╰─┤",
    "╰─╯"
]
":" = [
    " ",
    "╵",
    "╵"
]
