name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      
      - name: Install Dependencies
        run: nimble install -y

      - name: Compile Binary
        run: nim c -d:release --app:console src/tickterm.nim

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/tickterm
